#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt install nginx -y
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
replace="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n;"
sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default
sudo service nginx restart
