#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt install nginx -y
sudo chown -R ubuntu /usr/share/nginx/html
echo "Ceci n'est pas une page" > /var/www/html/index.nginx-debian.html/404.html
# replace="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
# sudo sed -i "53i\ $replace" /etc/nginx/sites-available/default
sudo sed -i "/rewrite*/a \\\n\\terror_page 404 /404.html;\\n\\n\\tlocation = /404.html {\\n\\t\\tinternal;\\n\\t}"\
	 etc/nginx/sites-available/default
sudo service nginx restart
