#!/usr/bin/env bash
# Web debugging 2
sudo pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "1 i user nginx;" /etc/nginx/nginx.conf
sed -i "s/8080/80/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
